services:
    catalogue:
      build: ./catalogue
      image:  josh3626/catalogue:1.0.0
      container_name: catalogue
      depends_on:
      - mongodb

    user  :
      build: ./user
      image: josh3626/user:1.0.0
      container_name: user
      depends_on:
      - redis
      - mongodb

    cart:
      build: ./cart
      image: josh3626/cart:1.0.0
      container_name: cart
      depends_on:
      - catalogue
      - redis

    shipping:
      build: ./shipping
      image: josh3626/shipping:1.0.0
      container_name: shipping
      depends_on:
      - mysql
      - cart

    payment:
      build: ./payment
      image: josh3626/payment:1.0.0
      container_name: payment
      depends_on:
      - user
      - cart
      - rabbitmq


    mongodb:
      build: ./mongodb
      image: josh3626/mongodb:1.0.0
      container_name: mongodb

    redis:
      image: redis:7.0
      container_name: redis

    mysql:
      build: ./mysql
      image: josh3626/mysql:1.0.0
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: Roboshop@1

    rabbitmq:
      image: rabbitmq:3
      container_name: rabbitmq
      environment:
        RABBITMQ_DEFAULT_USER: roboshop
        RABBITMQ_DEFAULT_PASS: roboshop123
      



    frontend:
      build: ./frontend
      image: josh3626/frontend:1.0.0
      container_name: frontend
      ports:
      - "80:80"
      depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
    
networks:
  default:
    driver: bridge
    name  : roboshop
    external: false
    

